export const FILTERS = {
    YEAR: [
        "None",
        "2020s",
        "2010s",
        "2000s",
        "1990s",
        "1980s",
        "1970s",
        "1960s",
        "1950s",
        "1940s",
        "later",
    ],

    GENRE: [
        "None",
        "Fiction",
        "Non-Fiction",
        "Science Fiction",
        "Fantasy",
        "Mystery",
        "Thriller",
        "Romance",
        "Biography",
        "History",
        "Self-Help",
        "Poetry",
        "Children's",
    ],
    OTHER: ["None", "By rating", "By editions"],
};
