export const FILTERS = {
    YEAR: [
        "2020s",
        "2010s",
        "2000s",
        "1990s",
        "1980s",
        "1970s",
        "1960s",
        "1950s",
        "1940s",
        "later",
    ],
    RATING: ["9+", "8-9", "7-8", "6-7", "5-6", "4-5", "3-4", "below 3"],

    POPULAR: [
        "Most Popular",
        "Trending",
        "Best Sellers",
        "Most Discussed",
        "Recently Added",
    ],
    GENRE: [
        "Fiction",
        "Non-Fiction",
        "Science Fiction",
        "Fantasy",
        "Mystery",
        "Thriller",
        "Romance",
        "Biography",
        "History",
        "Self-Help",
        "Poetry",
        "Children's",
    ],
};
